baseURL = 'https://andiputraw.github.io/tandichat-docs/'
canonifyurls = true
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-whisper-theme'
[params]
    homepage_button_link = '/docs'
    homepage_button_text = 'See the Docs'
    homepage_intro = 'REST API documentation for Tandichat server side. Build with hugo.'
    [params.logo]
        standard = '/images/logo.png'
        mobile = '/images/logo.png'